name: Fluxo de Trabalho para Pull Request

on:
  pull_request:
    branches:
      - main  # ou a branch para a qual você está fazendo o PR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checando o código
        uses: actions/checkout@v2

      - name: Trocando para a branch do PR
        run: git checkout ${{ github.head_ref }}  # Para garantir que estamos na branch do PR

      - name: Instalando o Node.js versão 21
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # ou qualquer versão do Node.js que você precise

      - name: Instalando dependências
        run: npm install

      - name: Executando testes
        run: npm run test

      - name: Executando testes de cobertura
        run: npm run test:coverage
