name: Meu primeiro workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Instalando dependências
        run: npm i -d

      - name: Executando testes
        run: npm run test   

      - name: Executando testes de cobertura
        run: npm run test:coverage
